### PR TITLE
Resolve #37

### LINKED ISSUE #37: Wrong format for invalid errors
Rails 7, Ruby 3

image

### PR DESCRIPTION
**Pull request by atagunay**
- fixed detail and source values
- Resolves #37

### CODE REVIEW

**Comment by atagunay** [comment]
@swilgosz

**Review by swilgosz — COMMENTED** [review]
Thank you!

Is it possible for you to add a test example catching this behavior?

**Comment by atagunay** [comment]
First of all, I added a validation into the my model
```ruby
class SportCenter < ApplicationRecord
  validates :name,
            uniqueness: true
```

Then I created controller
```ruby
  def create
    sport_center = SportCenter.create!(sport_center_params)
    render json: serializer.new(sport_center), status: :ok
  end
```

I created a error module and application controller include this module
```ruby
module Error
  module ErrorHandler
    include JsonapiErrorsHandler

    def self.included(clazz)
      clazz.class_eval do
        ErrorMapper.map_errors!({
                                  'ActiveRecord::RecordNotFound' => 'JsonapiErrorsHandler::Errors::NotFound'
                                })

        rescue_from ::StandardError,
                    with: lambda { |e| handle_error(e) }

        rescue_from ActionController::ParameterMissing,
                    with: lambda { |e| manage_error(e, 400, 'Missing Params', '/request/url', 'bad_request') }

        rescue_from ActiveRecord::RecordInvalid,
                    with: lambda { |e| handle_validation_error(e) }

        rescue_from ActiveModel::ValidationError,
                    with: lambda { |e| handle_validation_error(e) }


      end
    end

    private

    def manage_error(exception, status_code, title, pointer, status)
      render json: { errors:
                       [
                         "status": status_code,
                         "title": title,
                         "detail": exception.message,
                         "source": {"pointer": pointer}
                       ]
      }, status: :"#{status}"
    end

    def handle_validation_error(error)
      error_model = error.try(:model) || error.try(:record)
      mapped = JsonapiErrorsHandler::Errors::Invalid.new(errors: error_model.errors)
      render_error(mapped)
    end

  end
end
```

If program come across RecordInvalid or ValidationError, it handle with ```handle_validation_error``` method. But this method render wrong values. If I try to create new model with non-unique name. I just see this format:

image

After my solution, new format looks like correct:
image

**Comment by atagunay** [comment]
Have you any update for this pr? @swilgosz

**Comment by swilgosz** [comment]
Hey, sorry, only today got the time to take care of this. On it.

**Pull request closed without merging**
